import type { TenderProject } from './types';

export const INITIAL_PROJECTS: TenderProject[] = [
  {
    id: 'proj-nhai-088',
    nitNumber: 'NIT-NHAI-NCR-2026-088',
    title: 'Construction of 6-Lane Flyover & Bridge Superstructure on NH-48',
    department: 'National Highways Authority of India (NHAI)',
    estimatedValue: '₹148.50 Crores',
    lastModified: 'Just now',
    recencyTimestamp: Date.now() - 1000 * 60 * 5,
    status: 'NEEDS_REVIEW',
    complianceScore: 78,
    hasPdfUploaded: true,
    pdfFileName: 'MOCK_GOVERNMENT_TENDER_NIT_2026.pdf',
    description: 'EPC procurement for viaduct spans, pier caps, RCC deck slabs, and intelligent highway surveillance for the Delhi-Gurgaon highway corridor.',
    clauses: [
      {
        clauseId: 'cl-1',
        clauseNumber: 'Clause 4.1.2',
        title: 'Ordinary Portland Cement (OPC) 43 Grade',
        citedStandard: 'IS 8112:1989',
        status: 'WITHDRAWN',
        recommendedStandard: 'IS 269:2015',
        aiRecommendation: 'Standard IS 8112 was officially withdrawn in 2015 and consolidated into IS 269:2015 Clause 5.1 under the Cement Quality Control Order (GSR 739(E)).',
        userDecision: 'PENDING',
        page: 1,
        alternatives: [
          { standard: 'IS 269:2015', title: 'Ordinary Portland Cement (33, 43, 53)', description: 'Recommended active consolidated standard covering 43 Grade OPC.', tag: 'Primary / Recommended' },
          { standard: 'IS 1489 (Part 1):2015', title: 'Portland Pozzolana Cement (Fly Ash)', description: 'Permitted low-heat, high-durability option under IRC 112 bridge code.', tag: 'Eco Alternative' },
          { standard: 'IS 455:2015', title: 'Portland Slag Cement', description: 'Permitted option for high sulphate or marine environments.', tag: 'Alternative' },
        ],
      },
      {
        clauseId: 'cl-2',
        clauseNumber: 'Clause 4.2.5',
        title: 'High Yield Strength Deformed (HYSD) Rebar',
        citedStandard: 'IS 1786:1985 Fe 415',
        status: 'OUTDATED',
        recommendedStandard: 'IS 1786:2008 Grade Fe 500D',
        aiRecommendation: 'Fe 415 under the 1985 edition lacks ductility thresholds mandated by IS 13920:2016 for Seismic Zones IV & V. Upgrade to Fe 500D with uniform elongation ≥ 5%.',
        userDecision: 'PENDING',
        page: 1,
        alternatives: [
          { standard: 'IS 1786:2008 Fe 500D', title: 'High Ductility TMT Rebar (Fe 500D)', description: 'Mandatory standard for high-seismic bridge superstructures.', tag: 'Primary / Recommended' },
          { standard: 'IS 1786:2008 Fe 550D', title: 'High Strength Rebar (Fe 550D)', description: 'Higher yield strength for heavy-span girder reinforcement.', tag: 'Heavy Duty' },
        ],
      },
      {
        clauseId: 'cl-3',
        clauseNumber: 'Clause 6.3.1',
        title: 'HDPE Utility Drainage & Rainwater Pipes',
        citedStandard: 'IS 4984:1995 PE-80',
        status: 'AMENDMENT_NEEDED',
        recommendedStandard: 'IS 4984:2016 Amd 3 PE-100',
        aiRecommendation: 'IS 4984:1995 was superseded by IS 4984:2016. High-density resin PE-100 is required for hydrostatic durability under Ministry QCO 2021.',
        userDecision: 'PENDING',
        page: 1,
        alternatives: [
          { standard: 'IS 4984:2016 Amd 3', title: 'HDPE Pipes for Water Supply (PE-100)', description: 'Current active revision with latest hydrostatic burst test limits.', tag: 'Primary / Recommended' },
        ],
      },
      {
        clauseId: 'cl-4',
        clauseNumber: 'Clause 7.1.4',
        title: 'Structural Steel Plates for Composite Girders',
        citedStandard: 'IS 2062:2011 Grade E250 Quality A',
        status: 'ACTIVE',
        recommendedStandard: 'IS 2062:2011 Grade E250',
        aiRecommendation: 'Active and compliant Indian Standard under Steel QCO. Verify allied Charpy V-notch impact testing to IS 1757.',
        userDecision: 'APPROVED',
        chosenStandard: 'IS 2062:2011 Grade E250',
        page: 1,
        alternatives: [
          { standard: 'IS 2062:2011 Grade E250', title: 'Hot Rolled Structural Steel E250', description: 'Standard compliant structural grade.', tag: 'Active' },
        ],
      },
      {
        clauseId: 'cl-5',
        clauseNumber: 'Clause 9.2.0',
        title: 'Highway Traffic Surveillance IP CCTV Cameras',
        citedStandard: 'Uncertified Specifications',
        status: 'MISSING_STANDARD',
        recommendedStandard: 'IS 13252 (Part 1) & IS 16842:2020',
        aiRecommendation: 'Surveillance equipment must possess mandatory MeitY Compulsory Registration Scheme (CRS) certification under IS 13252 (Part 1) and video stream standard IS 16842.',
        userDecision: 'PENDING',
        page: 2,
        alternatives: [
          { standard: 'IS 13252 (Part 1) / IS 16842', title: 'BIS CRS Electronics Safety & CCTV Spec', description: 'Mandatory statutory CRS registration under Electronics Order.', tag: 'Statutory Mandate' },
        ],
      },
    ],
  },
  {
    id: 'proj-cpwd-042',
    nitNumber: 'NIT-CPWD-AIIMS-2026-042',
    title: 'Modernization & Electrification of Surgical Wing, AIIMS Delhi',
    department: 'Central Public Works Department (CPWD)',
    estimatedValue: '₹42.80 Crores',
    lastModified: '4 hours ago',
    recencyTimestamp: Date.now() - 1000 * 60 * 60 * 4,
    status: 'COMPLIANT',
    complianceScore: 100,
    hasPdfUploaded: false,
    description: 'Comprehensive retrofitting of emergency trauma units, clean-room HVAC, fire doors, and hospital-grade electrical safety compliance.',
    clauses: [
      {
        clauseId: 'cl-cpwd-1',
        clauseNumber: 'Clause 3.1.0',
        title: 'Fire Rated Metal Doorsets (2 Hours)',
        citedStandard: 'IS 3614:2021',
        status: 'ACTIVE',
        recommendedStandard: 'IS 3614:2021',
        aiRecommendation: 'Fully compliant with National Building Code (NBC 2016 Part 4) and active standard IS 3614:2021.',
        userDecision: 'APPROVED',
        chosenStandard: 'IS 3614:2021',
        alternatives: [],
      },
      {
        clauseId: 'cl-cpwd-2',
        clauseNumber: 'Clause 5.2.4',
        title: 'Low Smoke Zero Halogen (FRLS-H) Copper Cables',
        citedStandard: 'IS 694:2010',
        status: 'ACTIVE',
        recommendedStandard: 'IS 694:2010',
        aiRecommendation: 'Meets mandatory safety parameters for healthcare facilities. Allied testing: IS 10810 (Oxygen index ≥ 29%).',
        userDecision: 'APPROVED',
        chosenStandard: 'IS 694:2010',
        alternatives: [],
      },
    ],
  },
  {
    id: 'proj-dfccil-119',
    nitNumber: 'NIT-MOR-DFCCIL-2026-119',
    title: 'Dedicated Freight Corridor Track Laying & Pre-Stressed Sleepers',
    department: 'Ministry of Railways (DFCCIL)',
    estimatedValue: '₹310.00 Crores',
    lastModified: 'Yesterday',
    recencyTimestamp: Date.now() - 1000 * 60 * 60 * 24,
    status: 'NEEDS_REVIEW',
    complianceScore: 84,
    hasPdfUploaded: false,
    description: 'Heavy haul freight corridor package from Rewari to Dadri including 25-tonne axle load ballastless track and PSC turnouts.',
    clauses: [
      {
        clauseId: 'cl-dfc-1',
        clauseNumber: 'Clause 2.1.8',
        title: 'Pre-Stressed Concrete Sleepers (Heavy Axle 25T)',
        citedStandard: 'IS 1343:1980',
        status: 'OUTDATED',
        recommendedStandard: 'IS 1343:2012',
        aiRecommendation: 'IS 1343:1980 superseded by IS 1343:2012 (Code of Practice for Pre-stressed Concrete). Required for 25T axle loading fatigue limits.',
        userDecision: 'PENDING',
        alternatives: [
          { standard: 'IS 1343:2012', title: 'Pre-Stressed Concrete Code of Practice', description: 'Updated limit state design code.', tag: 'Primary / Recommended' },
        ],
      },
    ],
  },
  {
    id: 'proj-dmrc-071',
    nitNumber: 'NIT-DMRC-PHASE4-071',
    title: 'Underground Metro Tunnel Jet Ventilation Fans & Emergency Dampers',
    department: 'Delhi Metro Rail Corporation (DMRC)',
    estimatedValue: '₹88.20 Crores',
    lastModified: '3 days ago',
    recencyTimestamp: Date.now() - 1000 * 60 * 60 * 72,
    status: 'PUBLISHED',
    complianceScore: 96,
    hasPdfUploaded: false,
    description: 'Supply, installation, and testing of high-temperature reversible axial tunnel booster fans for Aerocity-Tughlakabad underground metro corridor.',
    clauses: [
      {
        clauseId: 'cl-dmrc-1',
        clauseNumber: 'Clause 8.4.1',
        title: 'High Temperature Jet Fans (400°C for 2 Hours)',
        citedStandard: 'IS/ISO 5801:2017 & EN 12101-3',
        status: 'ACTIVE',
        recommendedStandard: 'IS/ISO 5801:2017',
        aiRecommendation: 'Standard verified for subterranean fire smoke extraction.',
        userDecision: 'APPROVED',
        chosenStandard: 'IS/ISO 5801:2017',
        alternatives: [],
      },
    ],
  },
];
